name: Model train

on:
  push:
    branches:
      - main
    # paths:
    #   - 'notebook/data'
    paths-ignore:
      - 'README.md'
      - 'new_folder'

jobs:
  Train-model:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print the path to the root directory
      run: echo $GITHUB_WORKSPACE

    - name: Install dependencies
      run: |
        cd ./
        pip install -r requirements.txt 

    - name: Print the path to the root directory
      run: echo $GITHUB_WORKSPACE

    - name: Train model
      env:
        FULL_ACCESS: ${{ secrets.FULL_ACCESS }}
      run: |
        cd ./
        python full_train.py