name: Model train

on:
  push:
    branches:
      - main
    # paths:
    #   - 'notebook/data'
    paths-ignore:
      - 'README.md'

jobs:
  Train-model:
    runs-on: ubuntu-latest
    steps:
      - name: Add
        run: |
          python add.py
    # - name: Checkout code
    #   uses: actions/checkout@v2

    - name: Print the path to the root directory
      run: echo $GITHUB_WORKSPACE

    # - name: Install dependencies
    #   run: |
    #     cd ./
    #     pip install -r requirements.txt 

    # - name: Print the path to the root directory
    #   run: echo $GITHUB_WORKSPACE

    # - name: Train model
    #   run: |
    #     cd ./
    #     python full_train.py