name: Provision and Deploy

# on:
#   workflow_dispatch:
#     inputs:
#       ec2_name:
#         description: EC2 name
#         required: true
#         default: 'Otaku'
#         type: string

on:
  push:
    branches:
      - main

        
  deploy_ec2:
    needs: provision_ec2
    runs-on: ubuntu-latest
    steps:
      - name: Copy files to EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "dist/app"
          target: "/home/ec2-user/app"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip -y
          pip3 install virtualenv
          virtualenv env
          source env/bin/activate
          pip3 install -r requirements.txt