name: Provision and Deploy

on:
  push:
    branches:
      - main

jobs:
  provision_ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Provision EC2 Instance
        uses: ./provision_ec2.yaml
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}

      - name: Wait for EC2 instance to start
        run: sleep 30s

  deploy_ec2:
    needs: provision_ec2
    runs-on: ubuntu-latest
    steps:
      - name: Copy files to EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "dist/app"
          target: "/home/ec2-user/app"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip -y
          pip3 install virtualenv
          virtualenv env
          source env/bin/activate
          pip3 install -r requirements.txt