name: Provision t3.micro EC2
on:
  workflow_dispatch:
    inputs:
      ec2_name:
        description: EC2 name
        required: true
        default: 'Otaku'
        type: string

jobs:
  provision-ec2:
    runs-on: ubuntu-latest
    outputs:
      ec2_public_ip: ${{ steps.apply.outputs.ec2_public_ip }}
      ssh_user: ${{ steps.apply.outputs.ssh_user }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install PyInstaller
        run: pip install pyinstaller
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "${{ secrets.TF_USER_AWS_KEY }}"
          aws-secret-access-key: "${{ secrets.TF_USER_AWS_SECRET }}"
          aws-region: us-east-2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Apply
        id: apply
        env:
          TF_VAR_ec2_name: ${{ github.event.inputs.ec2_name }}
        run: |
          cd tf-example/
          terraform init
          terraform validate
          terraform plan
          terraform apply -auto-approve
      - name: Set secrets
        run: |
          echo "::set-secret name=EC2_HOST::${{ steps.apply.outputs.ec2_public_ip }}"
          echo "::set-secret name=EC2_USER::${{ steps.apply.outputs.ssh_user }}"
      - name: Package Flask app
        run: |
          cd .
          pyinstaller --onefile app.py
      - name: Check if executable file was generated
        run: |
          if [ -f "/home/runner/work/ec2/ec2/dist/app" ]; then
            echo "Executable file found!"
          else
            echo "ERROR: Executable file not found!"
          fi
      - name: Upload executable as artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: dist/app
